// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROG6212POE.Models
{
    [Table("module")]
    public partial class Module
    {
        [Key]
        [Column("module_id")]
        public int ModuleId { get; set; }
        [Required]
        [Column("module_code")]
        [StringLength(20)]
        [Unicode(false)]
        [Display(Name = "Module Code")]
        public string ModuleCode { get; set; }
        [Required]
        [Column("module_name")]
        [StringLength(40)]
        [Unicode(false)]
        [Display(Name = "Module Name")]
        public string ModuleName { get; set; }
        [Column("number_of_credits")]
        [Display(Name = "Number of Credits")]
        public int NumberOfCredits { get; set; }
        [Column("weekly_hours")]
        [Display(Name = "Class Hours per Week")]
        public int WeeklyHours { get; set; }
        [Column("self_study_hours")]
        [Display(Name = "Remaining Study Hours")]
        public int SelfStudyHours { get; set; }
        [Column("total_self_study_hours")]
        [Display(Name = "Total Study Hours")]
        public int TotalSelfStudyHours { get; set; }
        [Column("weekDayName")]
        [Display(Name = "Assigned Weekday")]
        public string WeekDayName { get; set; }
        [Column("users_id")]
        public int UsersId { get; set; }

        [ForeignKey("UsersId")]
        [InverseProperty("Modules")]
        public virtual RegisteredUser Users { get; set; }
    }
}