// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PROG6212POE.Models
{
    public partial class PROGPOEContext : DbContext
    {
        public PROGPOEContext()
        {
        }

        public PROGPOEContext(DbContextOptions<PROGPOEContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<RegisteredUser> RegisteredUsers { get; set; }
        public virtual DbSet<SelfStudyTracker> SelfStudyTrackers { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=lab000000\\SQLEXPRESS;Initial Catalog=PROGPOE;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Module>(entity =>
            {
                entity.HasOne(d => d.Users)
                    .WithMany(p => p.Modules)
                    .HasForeignKey(d => d.UsersId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__module__users_id__07C12930");
            });

            modelBuilder.Entity<RegisteredUser>(entity =>
            {
                entity.HasKey(e => e.UsersId)
                    .HasName("PK__Register__EAA7D14B491F5C5F");
            });

            modelBuilder.Entity<SelfStudyTracker>(entity =>
            {
                entity.HasKey(e => e.TrackerId)
                    .HasName("PK__SelfStud__AB2F888146C86AAE");
            });

            modelBuilder.Entity<Semester>(entity =>
            {
                entity.HasOne(d => d.Users)
                    .WithMany(p => p.Semesters)
                    .HasForeignKey(d => d.UsersId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__semester__users___04E4BC85");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}