// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROG6212POE.Models
{
    [Table("SelfStudy_Tracker")]
    public partial class SelfStudyTracker
    {
        [Key]
        [Column("tracker_id")]
        public int TrackerId { get; set; }
        [Required]
        [Column("moduleName")]
        [StringLength(30)]
        [Unicode(false)]
        [Display(Name = "Module Name")]
        public string ModuleName { get; set; }
        [Column("studyHours")]
        [Display(Name = "Hours Studied")]
        public int StudyHours { get; set; }
        [Column("currentDate", TypeName = "datetime")]
        [Display(Name = "Date")]
        public DateTime CurrentDate { get; set; }
    }
}