// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PROG6212POE.Models
{
    [Table("semester")]
    public partial class Semester
    {
        [Key]
        [Column("semester_id")]
        public int SemesterId { get; set; }
        [Column("semester_weeks")]
        [Display(Name ="Number of Weeks in Semester")]
        public int SemesterWeeks { get; set; }
        [Column("semester_date", TypeName = "date")]
        [Display(Name = "Semester Start Date")]
        public DateTime SemesterDate { get; set; }
        [Column("users_id")]
        public int UsersId { get; set; }

        [ForeignKey("UsersId")]
        [InverseProperty("Semesters")]
        public virtual RegisteredUser Users { get; set; }
    }
}